# Workflow Name
name : First Workflow
# Trigger
on : push

jobs:
  Hello-job:
     # runner - Github hosted
     runs-on : ubuntu-latest
     steps:
       - name : Hello World
         run : echo "Hello World"
     
